config/routes.rb
Rails.application.routes.draw do
  resources :departures, only: [:index]

  resources :schedule_import, only: [:index]

  root to: 'departures#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departure.rb
# Models a single departure
class Departure < ApplicationRecord
  STATUSES = [
    'On Time', 'Cancelled', 'Arriving', 'End', 'Now Boarding',
    'Info to follow', 'Arrived', 'All Aboard', 'TBD', 'Departed', 'Delayed',
    'Late', 'Hold '
  ].freeze

  belongs_to :origin, foreign_key: 'origin_id', class_name: 'Stop'
  belongs_to :destination, foreign_key: 'destination_id', class_name: 'Stop'

  validates :origin_id, presence: true
  validates :destination_id, presence: true
  validates :scheduled_time, presence: true
  validates :status, inclusion: { in: STATUSES }

  validates :trip, uniqueness: { scope: [:origin_id, :destination_id] }
end

app/models/stop.rb
class Stop < ApplicationRecord
  validates :stop_name, uniqueness: true

  # shim to our id for the stop_id in General Transit Feed Specification
  def stop_id
    id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departures_controller.rb
class DeparturesController < ApplicationController
  def index
    @display = DepartureIndex.new
  end
end

app/controllers/schedule_import_controller.rb
class ScheduleImportController < ApplicationController
  require './lib/csv_importer.rb'

  # GET index
  # import the latest schedule info and retirect to the departure board
  def index
    Departure.destroy_all
    CsvImporter.new(uri: SCHEDULE_CSV_URI).import

    redirect_to departures_path,
                flash: { notice: t('controller.schedule_import.success') }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/departures/index.html.haml
= stylesheet_link_tag 'departures'

.container.departure-board
  %hr.invisible
  .row
    .col-md-3
      %h5= @display.today_day
      %h5= @display.today_date
    .col-md-6.text-md-center
      %h4 Boston Station Departures
    .col-md-3.text-md-right
      %h5 CURRENT TIME
      %h5= @display.curent_time
  %hr.invisible
  %table.table.table-inverse.table-hover
    %thead
      %tr
        %th Time
        %th Origin
        %th Destination
        %th Trip #
        %th Track #
        %th Status
    %tbody
      - @display.departures.each do |departure_display|
        %tr
          %td= departure_display.time
          %td= departure_display.departure.origin.stop_name
          %td= departure_display.departure.destination.stop_name
          %td= departure_display.departure.trip
          %td= departure_display.track
          %td= departure_display.departure.trip
%hr.invisible
%hr.invisible
= link_to 'Fetch Latest Departures', schedule_import_index_path, class: 'btn btn-secondary static-btn'

app/views/layouts/_flash.html.haml
- if flash[:notice]
  .alert.alert-success.alert-dismissible.fade.in.text-md-center{:role => "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
    = flash[:notice]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MbtaDepartures
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'layouts'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield